# Pandas

Pandas is a Python module that is designed for user-friendly data analysis. It runs on top of a key Python module viz. Numpy. Pandas has become very popular among data scientists.

A quick comment on Pandas vs. Numpy (both are essentially data handling and analysis libraries). The core data structure in Numpy is a multidimensional homogeneous array - think of an n-dimensional matrix of real numbers. Numpy comes with a wide range of mathematical tools to use on such arrays. The main data structure in Pandas is the DataFrame which is tabular i.e. akin to the familiar spreadsheet. Pandas is optimised to handle and manipulate tabular data. It also meshes well with date & time
variables making it convenient for time series operations. One can access various type of data files (e.g. csv, xlsx, txt, SQL etc) using Pandas, organise the data for analysis, and then use Numpy and Scipy functions to carry out the analyses. For the latest on Pandas and to read detailed documentation, go to https://pandas.pydata.org .

Please read through a quick and helpful guide for Pandas beginners: https://pandas.pydata.org/docs/user_guide/10min.html 

To get access to many useful Python modules, such as Numpy and Pandas, you have to tell Python to import these. The import X as Y statement instructs the current Python environment to seach for module X and provide access to its code by giving it a name, Y, in the local scope. This later allows you to reference the imported module.

import numpy as np

import pandas as pd

Import of Pandas

In [4]:
import pandas as pd
import numpy as np # and also load numpy

Create a Series with numbers 50, 10 and 20

In [5]:
series1 = pd.Series([50, 10, 20])

In [6]:
series1

0    50
1    10
2    20
dtype: int64

Create another Series with colors

In [7]:
series2 = pd.Series(['red', 'purple', 'green', 'black'])

In [8]:
series2

0       red
1    purple
2     green
3     black
dtype: object

Create a DataFrame

In [9]:
dataf = pd.DataFrame()

In [10]:
dataf

Empty DataFrame
Columns: []
Index: []

In [11]:
dataf['Numbers'] = series1

In [12]:
dataf

   Numbers
0       50
1       10
2       20

In [13]:
dataf['Colours'] = series2

In [14]:
dataf

   Numbers Colours
0       50     red
1       10  purple
2       20   green

In [15]:
dataf[:2]

   Numbers Colours
0       50     red
1       10  purple

In [18]:
dataf[1:]

   Numbers Colours
1       10  purple
2       20   green

In [17]:
dataf[1:3]

   Numbers Colours
1       10  purple
2       20   green

In [19]:
dataf[:]

   Numbers Colours
0       50     red
1       10  purple
2       20   green

Reading in a DataFrame

In [20]:
#import pandas as pd
#import numpy as np

In [22]:
df = pd.read_csv(r'C:\Documents\Beer.csv')

In [23]:
print(df)

    place     pop2023  growthRate      area                 country cca3 cca2  \
0     203    10495295     0.00013     78865          Czech Republic  CZE   CZ
1      40     8958960     0.00216     83871                 Austria  AUT   AT
2     616    41026067     0.02933    312679                  Poland  POL   PL
3     642    19892812     0.01188    238391                 Romania  ROU   RO
4     276    83294633    -0.00090    357114                 Germany  DEU   DE
5     233     1322765    -0.00249     45227                 Estonia  EST   EE
6     440     2718352    -0.01153     65300               Lithuania  LTU   LT
7     516     2604172     0.01448    825615                 Namibia  NAM  NaN
8     703     5795199     0.02689     49037                Slovakia  SVK   SK
9     724    47519628    -0.00082    505992                   Spain  ESP   ES
10    372     5056935     0.00673     70273                 Ireland  IRL   IE
11    266     2436566     0.01991    267668                   Gabon  GAB   GA
12    178     6106869     0.02285    342000   Republic of the Congo  COG   CG
13    246     5545475     0.00085    338424                 Finland  FIN   FI
14    100     6687717    -0.01390    110879                Bulgaria  BGR   BG
15    840   339996563     0.00505   9372610           United States  USA   US
16    191     4008617    -0.00539     56594                 Croatia  HRV   HR
17     36    26439111     0.01000   7692024               Australia  AUS   AU
18    705     2119675    -0.00008     20273                Slovenia  SVN   SI
19    348    10156239     0.01896     93028                 Hungary  HUN   HU
20    528    17618299     0.00309     41850             Netherlands  NLD   NL
21     76   216422446     0.00515   8515767                  Brazil  BRA   BR
22    484   128455567     0.00746   1964375                  Mexico  MEX   MX
23     70     3210847    -0.00701     51209  Bosnia and Herzegovina  BIH   BA
24    208     5910913     0.00487     43094                 Denmark  DNK   DK
25    826    67736802     0.00338    242900          United Kingdom  GBR   GB
26    554     5228100     0.00826    270467             New Zealand  NZL   NZ
27    643   144444359    -0.00186  17098242                  Russia  RUS   RU
28    630     3260314     0.00243      8870             Puerto Rico  PRI   PR
29    710    60414495     0.00869   1221037            South Africa  ZAF   ZA
30     56    11686140     0.00259     30528                 Belgium  BEL   BE
31    124    38781291     0.00850   9984670                  Canada  CAN   CA
32    756     8796669     0.00643     41284             Switzerland  CHE   CH
33    591     4468087     0.01350     75417                  Panama  PAN   PA
34    752    10612086     0.00595    450295                  Sweden  SWE   SE
35    170    52085168     0.00407   1141748                Colombia  COL   CO
36    804    36744634    -0.07448    603500                 Ukraine  UKR   UA
37     32    45773884     0.00579   2780400               Argentina  ARG   AR
38    704    98858950     0.00685    331212                 Vietnam  VNM   VN
39    410    51784059    -0.00061    100210             South Korea  KOR   KR
40    392   123294513    -0.00530    377930                   Japan  JPN   JP
41    380    58870762    -0.00282    301336                   Italy  ITA   IT
42    250    64756584     0.00201    551695                  France  FRA   FR
43    156  1425671352    -0.00015   9706961                   China  CHN   CN
44    764    71801279     0.00145    513120                Thailand  THA   TH
45    608   117337368     0.01539    342353             Philippines  PHL   PH
46    356  1428627663     0.00808   3287590                   India  IND   IN

    ccn3         region                  subregion  landAreaKm   density  \
0    203         Europe             Eastern Europe     77198.5  135.9521
1     40         Europe             Western Europe     82520.0  108.5671
2    616         Europe             Eastern Europe    306130.0  134.0152
3    642         Europe             Eastern Europe    230080.0   86.4604
4    276         Europe             Western Europe    349390.0  238.4002
5    233         Europe            Northern Europe     42750.0   30.9419
6    440         Europe            Northern Europe     62620.0   43.4103
7    516         Africa         Sub-Saharan Africa    823290.0    3.1631
8    703         Europe             Eastern Europe     49035.0  118.1849
9    724         Europe            Southern Europe    499556.6   95.1236
10   372         Europe            Northern Europe     68890.0   73.4059
11   266         Africa         Sub-Saharan Africa    257670.0    9.4561
12   178         Africa         Sub-Saharan Africa    341500.0   17.8825
13   246         Europe            Northern Europe    303940.0   18.2453
14   100         Europe             Eastern Europe    108560.0   61.6039
15   840  North America           Northern America   9147420.0   37.1686
16   191         Europe            Southern Europe     55960.0   71.6336
17    36        Oceania  Australia and New Zealand   7692020.0    3.4372
18   705         Europe            Southern Europe     20136.4  105.2658
19   348         Europe             Eastern Europe     91260.0  111.2891
20   528         Europe             Western Europe     33670.0  523.2640
21    76  South America              Latin America   8358140.0   25.8936
22   484  North America              Latin America   1943950.0   66.0797
23    70         Europe            Southern Europe     51200.0   62.7119
24   208         Europe            Northern Europe     40000.0  147.7728
25   826         Europe            Northern Europe    241930.0  279.9851
26   554        Oceania  Australia and New Zealand    263310.0   19.8553
27   643         Europe             Eastern Europe  16376870.0    8.8200
28   630  North America                  Caribbean      8870.0  367.5664
29   710         Africa         Sub-Saharan Africa   1213090.0   49.8022
30    56         Europe             Western Europe     30280.0  385.9359
31   124  North America           Northern America   8965590.0    4.3256
32   756         Europe             Western Europe     39516.0  222.6103
33   591  North America              Latin America     74180.0   60.2330
34   752         Europe            Northern Europe    407283.5   26.0558
35   170  South America              Latin America   1109500.0   46.9447
36   804         Europe             Eastern Europe    579400.0   63.4184
37    32  South America              Latin America   2736690.0   16.7260
38   704           Asia         South-Eastern Asia    313429.0  315.4110
39   410           Asia               Eastern Asia     97600.0  530.5744
40   392           Asia               Eastern Asia    364500.0  338.2566
41   380         Europe            Southern Europe    295717.0  199.0780
42   250         Europe             Western Europe    547557.0  118.2646
43   156           Asia               Eastern Asia   9424702.9  151.2696
44   764           Asia         South-Eastern Asia    510890.0  140.5416
45   608           Asia         South-Eastern Asia    298170.0  393.5251
46   356           Asia         South Central Asia   2973190.0  480.5033

    densityMi  Rank  consmPerCap  consm  consmGals     pop2020  rank
0    352.1158    89        181.7   1946     514079    10708981     1
1    281.1889   100         96.8    872     230358     9006398     2
2    347.0993    37         96.0   3633     959737    37846611     3
3    223.9325    64         95.0   1828     482907    19237691     4
4    617.4564    19         92.5   7746    2046277    83783942     5
5     80.1394   156         84.4    112      29587     1326535     6
6    112.4326   142         83.4    227      59967     2722289     7
7      8.1925   145         83.4    212      56004     2540905     8
8    306.0990   116         82.2    449     118613     5459642     9
9    246.3702    32         81.6   3815    1007816    46754778    10
10   190.1214   125         81.0    400     105669     4937786    11
11    24.4914   146         80.0    178      47023     2225734    12
12    46.3156   113         78.8    435     114915     5518087    13
13    47.2553   118         77.2    428     113066     5540720    14
14   159.5540   110         75.6    525     138690     6948445    15
15    96.2666     3         72.8  24105    6367867   331002651    16
16   185.5311   130         72.1    296      78195     4105267    17
17     8.9024    55         71.6   1825     482114    25499884    18
18   272.6385   149         69.7    145      38305     2078938    19
19   288.2386    94         68.3    660     174354     9660351    20
20  1355.2538    72         67.1   1150     303798    17134872    21
21    67.0645     7         65.1  13847    3657990   212559417    22
22   171.1463    10         64.3   8287    2189194   128932753    23
23   162.4237   137         63.7    209      55212     3280819    24
24   382.7316   115         62.2    360      95102     5792202    25
25   725.1615    21         60.2   4088    1079935    67886011    26
26    51.4252   123         60.1    290      76610     4822233    27
27    22.8439     9         59.2   8646    2284032   145934462    28
28   951.9970   136         58.0    166      43853     2860853    29
29   128.9876    24         55.4   3284     867541    59308690    30
30   999.5741    82         53.1    615     162466    11589623    31
31    11.2032    38         52.4   1979     522796    37742154    32
32   576.5607   101         52.3    453     119670     8654622    33
33   156.0036   128         51.9    224      59175     4314767    34
34    67.4844    87         50.6    511     134992    10099265    35
35   121.5868    28         44.1   2246     593330    50882891    36
36   164.2537    41         43.0   1881     496908    43733762    37
37    43.3203    33         39.8   1797     474717    45195774    38
38   816.9145    16         39.5   3845    1015742    97338579    39
39  1374.1876    29         37.8   1936     511437    51269185    40
40   876.0845    12         34.9   4416    1166584   126476461    41
41   515.6121    25         31.2   1886     498228    60461826    42
42   306.3052    23         30.4   1984     524117    65273511    43
43   391.7884     2         25.1  36088    9533441  1439323776    44
44   364.0026    20         24.1   1680     443809    69799978    45
45  1019.2299    13         13.3   1462     386220   109581078    46
46  1244.5036     1          1.2   1686     445394  1380004385    47

In [24]:
df.head()

,place,pop2023,growthRate,area,country,cca3,cca2,ccn3,region,subregion,landAreaKm,density,densityMi,Rank,consmPerCap,consm,consmGals,pop2020,rank
0,203,10495295,0.00013,78865,Czech Republic,CZE,CZ,203,Europe,Eastern Europe,77198.5,135.9521,352.1158,89,181.7,1946,514079,10708981,1
1,40,8958960,0.00216,83871,Austria,AUT,AT,40,Europe,Western Europe,82520.0,108.5671,281.1889,100,96.8,872,230358,9006398,2
2,616,41026067,0.02933,312679,Poland,POL,PL,616,Europe,Eastern Europe,306130.0,134.0152,347.0993,37,96.0,3633,959737,37846611,3
3,642,19892812,0.01188,238391,Romania,ROU,RO,642,Europe,Eastern Europe,230080.0,86.4604,223.9325,64,95.0,1828,482907,19237691,4
4,276,83294633,-0.00090,357114,Germany,DEU,DE,276,Europe,Western Europe,349390.0,238.4002,617.4564,19,92.5,7746,2046277,83783942,5

In [25]:
df.head(10)

,place,pop2023,growthRate,area,country,cca3,cca2,ccn3,region,subregion,landAreaKm,density,densityMi,Rank,consmPerCap,consm,consmGals,pop2020,rank
0,203,10495295,0.00013,78865,Czech Republic,CZE,CZ,203,Europe,Eastern Europe,77198.5,135.9521,352.1158,89,181.7,1946,514079,10708981,1
1,40,8958960,0.00216,83871,Austria,AUT,AT,40,Europe,Western Europe,82520.0,108.5671,281.1889,100,96.8,872,230358,9006398,2
2,616,41026067,0.02933,312679,Poland,POL,PL,616,Europe,Eastern Europe,306130.0,134.0152,347.0993,37,96.0,3633,959737,37846611,3
3,642,19892812,0.01188,238391,Romania,ROU,RO,642,Europe,Eastern Europe,230080.0,86.4604,223.9325,64,95.0,1828,482907,19237691,4
4,276,83294633,-0.00090,357114,Germany,DEU,DE,276,Europe,Western Europe,349390.0,238.4002,617.4564,19,92.5,7746,2046277,83783942,5
5,233,1322765,-0.00249,45227,Estonia,EST,EE,233,Europe,Northern Europe,42750.0,30.9419,80.1394,156,84.4,112,29587,1326535,6
6,440,2718352,-0.01153,65300,Lithuania,LTU,LT,440,Europe,Northern Europe,62620.0,43.4103,112.4326,142,83.4,227,59967,2722289,7
7,516,2604172,0.01448,825615,Namibia,NAM,NaN,516,Africa,Sub-Saharan Africa,823290.0,3.1631,8.1925,145,83.4,212,56004,2540905,8
8,703,5795199,0.02689,49037,Slovakia,SVK,SK,703,Europe,Eastern Europe,49035.0,118.1849,306.0990,116,82.2,449,118613,5459642,9
9,724,47519628,-0.00082,505992,Spain,ESP,ES,724,Europe,Southern Europe,499556.6,95.1236,246.3702,32,81.6,3815,1007816,46754778,10

In [26]:
df.tail()

,place,pop2023,growthRate,area,country,cca3,cca2,ccn3,region,subregion,landAreaKm,density,densityMi,Rank,consmPerCap,consm,consmGals,pop2020,rank
42,250,64756584,0.00201,551695,France,FRA,FR,250,Europe,Western Europe,547557.0,118.2646,306.3052,23,30.4,1984,524117,65273511,43
43,156,1425671352,-0.00015,9706961,China,CHN,CN,156,Asia,Eastern Asia,9424702.9,151.2696,391.7884,2,25.1,36088,9533441,1439323776,44
44,764,71801279,0.00145,513120,Thailand,THA,TH,764,Asia,South-Eastern Asia,510890.0,140.5416,364.0026,20,24.1,1680,443809,69799978,45
45,608,117337368,0.01539,342353,Philippines,PHL,PH,608,Asia,South-Eastern Asia,298170.0,393.5251,1019.2299,13,13.3,1462,386220,109581078,46
46,356,1428627663,0.00808,3287590,India,IND,IN,356,Asia,South Central Asia,2973190.0,480.5033,1244.5036,1,1.2,1686,445394,1380004385,47

In [27]:
print(df.head())

   place   pop2023  growthRate    area         country cca3 cca2  ccn3  \
0    203  10495295     0.00013   78865  Czech Republic  CZE   CZ   203
1     40   8958960     0.00216   83871         Austria  AUT   AT    40
2    616  41026067     0.02933  312679          Poland  POL   PL   616
3    642  19892812     0.01188  238391         Romania  ROU   RO   642
4    276  83294633    -0.00090  357114         Germany  DEU   DE   276

   region       subregion  landAreaKm   density  densityMi  Rank  consmPerCap  \
0  Europe  Eastern Europe     77198.5  135.9521   352.1158    89        181.7
1  Europe  Western Europe     82520.0  108.5671   281.1889   100         96.8
2  Europe  Eastern Europe    306130.0  134.0152   347.0993    37         96.0
3  Europe  Eastern Europe    230080.0   86.4604   223.9325    64         95.0
4  Europe  Western Europe    349390.0  238.4002   617.4564    19         92.5

   consm  consmGals   pop2020  rank
0   1946     514079  10708981     1
1    872     230358   9006398     2
2   3633     959737  37846611     3
3   1828     482907  19237691     4
4   7746    2046277  83783942     5

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   place        47 non-null     int64
 1   pop2023      47 non-null     int64
 2   growthRate   47 non-null     float64
 3   area         47 non-null     int64
 4   country      47 non-null     object
 5   cca3         47 non-null     object
 6   cca2         46 non-null     object
 7   ccn3         47 non-null     int64
 8   region       47 non-null     object
 9   subregion    47 non-null     object
 10  landAreaKm   47 non-null     float64
 11  density      47 non-null     float64
 12  densityMi    47 non-null     float64
 13  Rank         47 non-null     int64
 14  consmPerCap  47 non-null     float64
 15  consm        47 non-null     int64
 16  consmGals    47 non-null     int64
 17  pop2020      47 non-null     int64
 18  rank         47 non-null     int64
dtypes: float64(5), int64(9), object(5)
memory usage: 7.1+ KB

In [29]:
df.shape

(47, 19)

In [30]:
df.dtypes

place            int64
pop2023          int64
growthRate     float64
area             int64
country         object
cca3            object
cca2            object
ccn3             int64
region          object
subregion       object
landAreaKm     float64
density        float64
densityMi      float64
Rank             int64
consmPerCap    float64
consm            int64
consmGals        int64
pop2020          int64
rank             int64
dtype: object

In [31]:
df.consmGals.sum()

40907836

In [32]:
Var1 = df['consmPerCap']

In [33]:
Var1

0     181.7
1      96.8
2      96.0
3      95.0
4      92.5
5      84.4
6      83.4
7      83.4
8      82.2
9      81.6
10     81.0
11     80.0
12     78.8
13     77.2
14     75.6
15     72.8
16     72.1
17     71.6
18     69.7
19     68.3
20     67.1
21     65.1
22     64.3
23     63.7
24     62.2
25     60.2
26     60.1
27     59.2
28     58.0
29     55.4
30     53.1
31     52.4
32     52.3
33     51.9
34     50.6
35     44.1
36     43.0
37     39.8
38     39.5
39     37.8
40     34.9
41     31.2
42     30.4
43     25.1
44     24.1
45     13.3
46      1.2
Name: consmPerCap, dtype: float64

In [34]:
Var1_v2 = df.consmPerCap
Var1_v2

0     181.7
1      96.8
2      96.0
3      95.0
4      92.5
5      84.4
6      83.4
7      83.4
8      82.2
9      81.6
10     81.0
11     80.0
12     78.8
13     77.2
14     75.6
15     72.8
16     72.1
17     71.6
18     69.7
19     68.3
20     67.1
21     65.1
22     64.3
23     63.7
24     62.2
25     60.2
26     60.1
27     59.2
28     58.0
29     55.4
30     53.1
31     52.4
32     52.3
33     51.9
34     50.6
35     44.1
36     43.0
37     39.8
38     39.5
39     37.8
40     34.9
41     31.2
42     30.4
43     25.1
44     24.1
45     13.3
46      1.2
Name: consmPerCap, dtype: float64

In [36]:
df[df.consmPerCap > 90]

,place,pop2023,growthRate,area,country,cca3,cca2,ccn3,region,subregion,landAreaKm,density,densityMi,Rank,consmPerCap,consm,consmGals,pop2020,rank
0,203,10495295,0.00013,78865,Czech Republic,CZE,CZ,203,Europe,Eastern Europe,77198.5,135.9521,352.1158,89,181.7,1946,514079,10708981,1
1,40,8958960,0.00216,83871,Austria,AUT,AT,40,Europe,Western Europe,82520.0,108.5671,281.1889,100,96.8,872,230358,9006398,2
2,616,41026067,0.02933,312679,Poland,POL,PL,616,Europe,Eastern Europe,306130.0,134.0152,347.0993,37,96.0,3633,959737,37846611,3
3,642,19892812,0.01188,238391,Romania,ROU,RO,642,Europe,Eastern Europe,230080.0,86.4604,223.9325,64,95.0,1828,482907,19237691,4
4,276,83294633,-0.00090,357114,Germany,DEU,DE,276,Europe,Western Europe,349390.0,238.4002,617.4564,19,92.5,7746,2046277,83783942,5

In [37]:
df = df.set_index('rank')

In [38]:
df

,place,pop2023,growthRate,area,country,cca3,cca2,ccn3,region,subregion,landAreaKm,density,densityMi,Rank,consmPerCap,consm,consmGals,pop2020
rank,,,,,,,,,,,,,,,,,,
1,203,10495295,0.00013,78865,Czech Republic,CZE,CZ,203,Europe,Eastern Europe,77198.5,135.9521,352.1158,89,181.7,1946,514079,10708981
2,40,8958960,0.00216,83871,Austria,AUT,AT,40,Europe,Western Europe,82520.0,108.5671,281.1889,100,96.8,872,230358,9006398
3,616,41026067,0.02933,312679,Poland,POL,PL,616,Europe,Eastern Europe,306130.0,134.0152,347.0993,37,96.0,3633,959737,37846611
4,642,19892812,0.01188,238391,Romania,ROU,RO,642,Europe,Eastern Europe,230080.0,86.4604,223.9325,64,95.0,1828,482907,19237691
5,276,83294633,-0.00090,357114,Germany,DEU,DE,276,Europe,Western Europe,349390.0,238.4002,617.4564,19,92.5,7746,2046277,83783942
6,233,1322765,-0.00249,45227,Estonia,EST,EE,233,Europe,Northern Europe,42750.0,30.9419,80.1394,156,84.4,112,29587,1326535
7,440,2718352,-0.01153,65300,Lithuania,LTU,LT,440,Europe,Northern Europe,62620.0,43.4103,112.4326,142,83.4,227,59967,2722289
8,516,2604172,0.01448,825615,Namibia,NAM,NaN,516,Africa,Sub-Saharan Africa,823290.0,3.1631,8.1925,145,83.4,212,56004,2540905
9,703,5795199,0.02689,49037,Slovakia,SVK,SK,703,Europe,Eastern Europe,49035.0,118.1849,306.0990,116,82.2,449,118613,5459642
10,724,47519628,-0.00082,505992,Spain,ESP,ES,724,Europe,Southern Europe,499556.6,95.1236,246.3702,32,81.6,3815,1007816,46754778
11,372,5056935,0.00673,70273,Ireland,IRL,IE,372,Europe,Northern Europe,68890.0,73.4059,190.1214,125,81.0,400,105669,4937786
12,266,2436566,0.01991,267668,Gabon,GAB,GA,266,Africa,Sub-Saharan Africa,257670.0,9.4561,24.4914,146,80.0,178,47023,2225734
13,178,6106869,0.02285,342000,Republic of the Congo,COG,CG,178,Africa,Sub-Saharan Africa,341500.0,17.8825,46.3156,113,78.8,435,114915,5518087
14,246,5545475,0.00085,338424,Finland,FIN,FI,246,Europe,Northern Europe,303940.0,18.2453,47.2553,118,77.2,428,113066,5540720
15,100,6687717,-0.01390,110879,Bulgaria,BGR,BG,100,Europe,Eastern Europe,108560.0,61.6039,159.5540,110,75.6,525,138690,6948445
16,840,339996563,0.00505,9372610,United States,USA,US,840,North America,Northern America,9147420.0,37.1686,96.2666,3,72.8,24105,6367867,331002651
17,191,4008617,-0.00539,56594,Croatia,HRV,HR,191,Europe,Southern Europe,55960.0,71.6336,185.5311,130,72.1,296,78195,4105267
18,36,26439111,0.01000,7692024,Australia,AUS,AU,36,Oceania,Australia and New Zealand,7692020.0,3.4372,8.9024,55,71.6,1825,482114,25499884
19,705,2119675,-0.00008,20273,Slovenia,SVN,SI,705,Europe,Southern Europe,20136.4,105.2658,272.6385,149,69.7,145,38305,2078938
20,348,10156239,0.01896,93028,Hungary,HUN,HU,348,Europe,Eastern Europe,91260.0,111.2891,288.2386,94,68.3,660,174354,9660351
21,528,17618299,0.00309,41850,Netherlands,NLD,NL,528,Europe,Western Europe,33670.0,523.2640,1355.2538,72,67.1,1150,303798,17134872
22,76,216422446,0.00515,8515767,Brazil,BRA,BR,76,South America,Latin America,8358140.0,25.8936,67.0645,7,65.1,13847,3657990,212559417
23,484,128455567,0.00746,1964375,Mexico,MEX,MX,484,North America,Latin America,1943950.0,66.0797,171.1463,10,64.3,8287,2189194,128932753
24,70,3210847,-0.00701,51209,Bosnia and Herzegovina,BIH,BA,70,Europe,Southern Europe,51200.0,62.7119,162.4237,137,63.7,209,55212,3280819
25,208,5910913,0.00487,43094,Denmark,DNK,DK,208,Europe,Northern Europe,40000.0,147.7728,382.7316,115,62.2,360,95102,5792202
26,826,67736802,0.00338,242900,United Kingdom,GBR,GB,826,Europe,Northern Europe,241930.0,279.9851,725.1615,21,60.2,4088,1079935,67886011
27,554,5228100,0.00826,270467,New Zealand,NZL,NZ,554,Oceania,Australia and New Zealand,263310.0,19.8553,51.4252,123,60.1,290,76610,4822233
28,643,144444359,-0.00186,17098242,Russia,RUS,RU,643,Europe,Eastern Europe,16376870.0,8.8200,22.8439,9,59.2,8646,2284032,145934462
29,630,3260314,0.00243,8870,Puerto Rico,PRI,PR,630,North America,Caribbean,8870.0,367.5664,951.9970,136,58.0,166,43853,2860853
30,710,60414495,0.00869,1221037,South Africa,ZAF,ZA,710,Africa,Sub-Saharan Africa,1213090.0,49.8022,128.9876,24,55.4,3284,867541,59308690
31,56,11686140,0.00259,30528,Belgium,BEL,BE,56,Europe,Western Europe,30280.0,385.9359,999.5741,82,53.1,615,162466,11589623
32,124,38781291,0.00850,9984670,Canada,CAN,CA,124,North America,Northern America,8965590.0,4.3256,11.2032,38,52.4,1979,522796,37742154
33,756,8796669,0.00643,41284,Switzerland,CHE,CH,756,Europe,Western Europe,39516.0,222.6103,576.5607,101,52.3,453,119670,8654622
34,591,4468087,0.01350,75417,Panama,PAN,PA,591,North America,Latin America,74180.0,60.2330,156.0036,128,51.9,224,59175,4314767
35,752,10612086,0.00595,450295,Sweden,SWE,SE,752,Europe,Northern Europe,407283.5,26.0558,67.4844,87,50.6,511,134992,10099265
36,170,52085168,0.00407,1141748,Colombia,COL,CO,170,South America,Latin America,1109500.0,46.9447,121.5868,28,44.1,2246,593330,50882891
37,804,36744634,-0.07448,603500,Ukraine,UKR,UA,804,Europe,Eastern Europe,579400.0,63.4184,164.2537,41,43.0,1881,496908,43733762
38,32,45773884,0.00579,2780400,Argentina,ARG,AR,32,South America,Latin America,2736690.0,16.7260,43.3203,33,39.8,1797,474717,45195774
39,704,98858950,0.00685,331212,Vietnam,VNM,VN,704,Asia,South-Eastern Asia,313429.0,315.4110,816.9145,16,39.5,3845,1015742,97338579
40,410,51784059,-0.00061,100210,South Korea,KOR,KR,410,Asia,Eastern Asia,97600.0,530.5744,1374.1876,29,37.8,1936,511437,51269185
41,392,123294513,-0.00530,377930,Japan,JPN,JP,392,Asia,Eastern Asia,364500.0,338.2566,876.0845,12,34.9,4416,1166584,126476461
42,380,58870762,-0.00282,301336,Italy,ITA,IT,380,Europe,Southern Europe,295717.0,199.0780,515.6121,25,31.2,1886,498228,60461826
43,250,64756584,0.00201,551695,France,FRA,FR,250,Europe,Western Europe,547557.0,118.2646,306.3052,23,30.4,1984,524117,65273511
44,156,1425671352,-0.00015,9706961,China,CHN,CN,156,Asia,Eastern Asia,9424702.9,151.2696,391.7884,2,25.1,36088,9533441,1439323776
45,764,71801279,0.00145,513120,Thailand,THA,TH,764,Asia,South-Eastern Asia,510890.0,140.5416,364.0026,20,24.1,1680,443809,69799978
46,608,117337368,0.01539,342353,Philippines,PHL,PH,608,Asia,South-Eastern Asia,298170.0,393.5251,1019.2299,13,13.3,1462,386220,109581078
47,356,1428627663,0.00808,3287590,India,IND,IN,356,Asia,South Central Asia,2973190.0,480.5033,1244.5036,1,1.2,1686,445394,1380004385

In [39]:
df = df.reset_index()

In [40]:
df

,rank,place,pop2023,growthRate,area,country,cca3,cca2,ccn3,region,subregion,landAreaKm,density,densityMi,Rank,consmPerCap,consm,consmGals,pop2020
0,1,203,10495295,0.00013,78865,Czech Republic,CZE,CZ,203,Europe,Eastern Europe,77198.5,135.9521,352.1158,89,181.7,1946,514079,10708981
1,2,40,8958960,0.00216,83871,Austria,AUT,AT,40,Europe,Western Europe,82520.0,108.5671,281.1889,100,96.8,872,230358,9006398
2,3,616,41026067,0.02933,312679,Poland,POL,PL,616,Europe,Eastern Europe,306130.0,134.0152,347.0993,37,96.0,3633,959737,37846611
3,4,642,19892812,0.01188,238391,Romania,ROU,RO,642,Europe,Eastern Europe,230080.0,86.4604,223.9325,64,95.0,1828,482907,19237691
4,5,276,83294633,-0.00090,357114,Germany,DEU,DE,276,Europe,Western Europe,349390.0,238.4002,617.4564,19,92.5,7746,2046277,83783942
5,6,233,1322765,-0.00249,45227,Estonia,EST,EE,233,Europe,Northern Europe,42750.0,30.9419,80.1394,156,84.4,112,29587,1326535
6,7,440,2718352,-0.01153,65300,Lithuania,LTU,LT,440,Europe,Northern Europe,62620.0,43.4103,112.4326,142,83.4,227,59967,2722289
7,8,516,2604172,0.01448,825615,Namibia,NAM,NaN,516,Africa,Sub-Saharan Africa,823290.0,3.1631,8.1925,145,83.4,212,56004,2540905
8,9,703,5795199,0.02689,49037,Slovakia,SVK,SK,703,Europe,Eastern Europe,49035.0,118.1849,306.0990,116,82.2,449,118613,5459642
9,10,724,47519628,-0.00082,505992,Spain,ESP,ES,724,Europe,Southern Europe,499556.6,95.1236,246.3702,32,81.6,3815,1007816,46754778
10,11,372,5056935,0.00673,70273,Ireland,IRL,IE,372,Europe,Northern Europe,68890.0,73.4059,190.1214,125,81.0,400,105669,4937786
11,12,266,2436566,0.01991,267668,Gabon,GAB,GA,266,Africa,Sub-Saharan Africa,257670.0,9.4561,24.4914,146,80.0,178,47023,2225734
12,13,178,6106869,0.02285,342000,Republic of the Congo,COG,CG,178,Africa,Sub-Saharan Africa,341500.0,17.8825,46.3156,113,78.8,435,114915,5518087
13,14,246,5545475,0.00085,338424,Finland,FIN,FI,246,Europe,Northern Europe,303940.0,18.2453,47.2553,118,77.2,428,113066,5540720
14,15,100,6687717,-0.01390,110879,Bulgaria,BGR,BG,100,Europe,Eastern Europe,108560.0,61.6039,159.5540,110,75.6,525,138690,6948445
15,16,840,339996563,0.00505,9372610,United States,USA,US,840,North America,Northern America,9147420.0,37.1686,96.2666,3,72.8,24105,6367867,331002651
16,17,191,4008617,-0.00539,56594,Croatia,HRV,HR,191,Europe,Southern Europe,55960.0,71.6336,185.5311,130,72.1,296,78195,4105267
17,18,36,26439111,0.01000,7692024,Australia,AUS,AU,36,Oceania,Australia and New Zealand,7692020.0,3.4372,8.9024,55,71.6,1825,482114,25499884
18,19,705,2119675,-0.00008,20273,Slovenia,SVN,SI,705,Europe,Southern Europe,20136.4,105.2658,272.6385,149,69.7,145,38305,2078938
19,20,348,10156239,0.01896,93028,Hungary,HUN,HU,348,Europe,Eastern Europe,91260.0,111.2891,288.2386,94,68.3,660,174354,9660351
20,21,528,17618299,0.00309,41850,Netherlands,NLD,NL,528,Europe,Western Europe,33670.0,523.2640,1355.2538,72,67.1,1150,303798,17134872
21,22,76,216422446,0.00515,8515767,Brazil,BRA,BR,76,South America,Latin America,8358140.0,25.8936,67.0645,7,65.1,13847,3657990,212559417
22,23,484,128455567,0.00746,1964375,Mexico,MEX,MX,484,North America,Latin America,1943950.0,66.0797,171.1463,10,64.3,8287,2189194,128932753
23,24,70,3210847,-0.00701,51209,Bosnia and Herzegovina,BIH,BA,70,Europe,Southern Europe,51200.0,62.7119,162.4237,137,63.7,209,55212,3280819
24,25,208,5910913,0.00487,43094,Denmark,DNK,DK,208,Europe,Northern Europe,40000.0,147.7728,382.7316,115,62.2,360,95102,5792202
25,26,826,67736802,0.00338,242900,United Kingdom,GBR,GB,826,Europe,Northern Europe,241930.0,279.9851,725.1615,21,60.2,4088,1079935,67886011
26,27,554,5228100,0.00826,270467,New Zealand,NZL,NZ,554,Oceania,Australia and New Zealand,263310.0,19.8553,51.4252,123,60.1,290,76610,4822233
27,28,643,144444359,-0.00186,17098242,Russia,RUS,RU,643,Europe,Eastern Europe,16376870.0,8.8200,22.8439,9,59.2,8646,2284032,145934462
28,29,630,3260314,0.00243,8870,Puerto Rico,PRI,PR,630,North America,Caribbean,8870.0,367.5664,951.9970,136,58.0,166,43853,2860853
29,30,710,60414495,0.00869,1221037,South Africa,ZAF,ZA,710,Africa,Sub-Saharan Africa,1213090.0,49.8022,128.9876,24,55.4,3284,867541,59308690
30,31,56,11686140,0.00259,30528,Belgium,BEL,BE,56,Europe,Western Europe,30280.0,385.9359,999.5741,82,53.1,615,162466,11589623
31,32,124,38781291,0.00850,9984670,Canada,CAN,CA,124,North America,Northern America,8965590.0,4.3256,11.2032,38,52.4,1979,522796,37742154
32,33,756,8796669,0.00643,41284,Switzerland,CHE,CH,756,Europe,Western Europe,39516.0,222.6103,576.5607,101,52.3,453,119670,8654622
33,34,591,4468087,0.01350,75417,Panama,PAN,PA,591,North America,Latin America,74180.0,60.2330,156.0036,128,51.9,224,59175,4314767
34,35,752,10612086,0.00595,450295,Sweden,SWE,SE,752,Europe,Northern Europe,407283.5,26.0558,67.4844,87,50.6,511,134992,10099265
35,36,170,52085168,0.00407,1141748,Colombia,COL,CO,170,South America,Latin America,1109500.0,46.9447,121.5868,28,44.1,2246,593330,50882891
36,37,804,36744634,-0.07448,603500,Ukraine,UKR,UA,804,Europe,Eastern Europe,579400.0,63.4184,164.2537,41,43.0,1881,496908,43733762
37,38,32,45773884,0.00579,2780400,Argentina,ARG,AR,32,South America,Latin America,2736690.0,16.7260,43.3203,33,39.8,1797,474717,45195774
38,39,704,98858950,0.00685,331212,Vietnam,VNM,VN,704,Asia,South-Eastern Asia,313429.0,315.4110,816.9145,16,39.5,3845,1015742,97338579
39,40,410,51784059,-0.00061,100210,South Korea,KOR,KR,410,Asia,Eastern Asia,97600.0,530.5744,1374.1876,29,37.8,1936,511437,51269185
40,41,392,123294513,-0.00530,377930,Japan,JPN,JP,392,Asia,Eastern Asia,364500.0,338.2566,876.0845,12,34.9,4416,1166584,126476461
41,42,380,58870762,-0.00282,301336,Italy,ITA,IT,380,Europe,Southern Europe,295717.0,199.0780,515.6121,25,31.2,1886,498228,60461826
42,43,250,64756584,0.00201,551695,France,FRA,FR,250,Europe,Western Europe,547557.0,118.2646,306.3052,23,30.4,1984,524117,65273511
43,44,156,1425671352,-0.00015,9706961,China,CHN,CN,156,Asia,Eastern Asia,9424702.9,151.2696,391.7884,2,25.1,36088,9533441,1439323776
44,45,764,71801279,0.00145,513120,Thailand,THA,TH,764,Asia,South-Eastern Asia,510890.0,140.5416,364.0026,20,24.1,1680,443809,69799978
45,46,608,117337368,0.01539,342353,Philippines,PHL,PH,608,Asia,South-Eastern Asia,298170.0,393.5251,1019.2299,13,13.3,1462,386220,109581078
46,47,356,1428627663,0.00808,3287590,India,IND,IN,356,Asia,South Central Asia,2973190.0,480.5033,1244.5036,1,1.2,1686,445394,1380004385

In [41]:
df.sort_index(ascending=False)

,rank,place,pop2023,growthRate,area,country,cca3,cca2,ccn3,region,subregion,landAreaKm,density,densityMi,Rank,consmPerCap,consm,consmGals,pop2020
46,47,356,1428627663,0.00808,3287590,India,IND,IN,356,Asia,South Central Asia,2973190.0,480.5033,1244.5036,1,1.2,1686,445394,1380004385
45,46,608,117337368,0.01539,342353,Philippines,PHL,PH,608,Asia,South-Eastern Asia,298170.0,393.5251,1019.2299,13,13.3,1462,386220,109581078
44,45,764,71801279,0.00145,513120,Thailand,THA,TH,764,Asia,South-Eastern Asia,510890.0,140.5416,364.0026,20,24.1,1680,443809,69799978
43,44,156,1425671352,-0.00015,9706961,China,CHN,CN,156,Asia,Eastern Asia,9424702.9,151.2696,391.7884,2,25.1,36088,9533441,1439323776
42,43,250,64756584,0.00201,551695,France,FRA,FR,250,Europe,Western Europe,547557.0,118.2646,306.3052,23,30.4,1984,524117,65273511
41,42,380,58870762,-0.00282,301336,Italy,ITA,IT,380,Europe,Southern Europe,295717.0,199.0780,515.6121,25,31.2,1886,498228,60461826
40,41,392,123294513,-0.00530,377930,Japan,JPN,JP,392,Asia,Eastern Asia,364500.0,338.2566,876.0845,12,34.9,4416,1166584,126476461
39,40,410,51784059,-0.00061,100210,South Korea,KOR,KR,410,Asia,Eastern Asia,97600.0,530.5744,1374.1876,29,37.8,1936,511437,51269185
38,39,704,98858950,0.00685,331212,Vietnam,VNM,VN,704,Asia,South-Eastern Asia,313429.0,315.4110,816.9145,16,39.5,3845,1015742,97338579
37,38,32,45773884,0.00579,2780400,Argentina,ARG,AR,32,South America,Latin America,2736690.0,16.7260,43.3203,33,39.8,1797,474717,45195774
36,37,804,36744634,-0.07448,603500,Ukraine,UKR,UA,804,Europe,Eastern Europe,579400.0,63.4184,164.2537,41,43.0,1881,496908,43733762
35,36,170,52085168,0.00407,1141748,Colombia,COL,CO,170,South America,Latin America,1109500.0,46.9447,121.5868,28,44.1,2246,593330,50882891
34,35,752,10612086,0.00595,450295,Sweden,SWE,SE,752,Europe,Northern Europe,407283.5,26.0558,67.4844,87,50.6,511,134992,10099265
33,34,591,4468087,0.01350,75417,Panama,PAN,PA,591,North America,Latin America,74180.0,60.2330,156.0036,128,51.9,224,59175,4314767
32,33,756,8796669,0.00643,41284,Switzerland,CHE,CH,756,Europe,Western Europe,39516.0,222.6103,576.5607,101,52.3,453,119670,8654622
31,32,124,38781291,0.00850,9984670,Canada,CAN,CA,124,North America,Northern America,8965590.0,4.3256,11.2032,38,52.4,1979,522796,37742154
30,31,56,11686140,0.00259,30528,Belgium,BEL,BE,56,Europe,Western Europe,30280.0,385.9359,999.5741,82,53.1,615,162466,11589623
29,30,710,60414495,0.00869,1221037,South Africa,ZAF,ZA,710,Africa,Sub-Saharan Africa,1213090.0,49.8022,128.9876,24,55.4,3284,867541,59308690
28,29,630,3260314,0.00243,8870,Puerto Rico,PRI,PR,630,North America,Caribbean,8870.0,367.5664,951.9970,136,58.0,166,43853,2860853
27,28,643,144444359,-0.00186,17098242,Russia,RUS,RU,643,Europe,Eastern Europe,16376870.0,8.8200,22.8439,9,59.2,8646,2284032,145934462
26,27,554,5228100,0.00826,270467,New Zealand,NZL,NZ,554,Oceania,Australia and New Zealand,263310.0,19.8553,51.4252,123,60.1,290,76610,4822233
25,26,826,67736802,0.00338,242900,United Kingdom,GBR,GB,826,Europe,Northern Europe,241930.0,279.9851,725.1615,21,60.2,4088,1079935,67886011
24,25,208,5910913,0.00487,43094,Denmark,DNK,DK,208,Europe,Northern Europe,40000.0,147.7728,382.7316,115,62.2,360,95102,5792202
23,24,70,3210847,-0.00701,51209,Bosnia and Herzegovina,BIH,BA,70,Europe,Southern Europe,51200.0,62.7119,162.4237,137,63.7,209,55212,3280819
22,23,484,128455567,0.00746,1964375,Mexico,MEX,MX,484,North America,Latin America,1943950.0,66.0797,171.1463,10,64.3,8287,2189194,128932753
21,22,76,216422446,0.00515,8515767,Brazil,BRA,BR,76,South America,Latin America,8358140.0,25.8936,67.0645,7,65.1,13847,3657990,212559417
20,21,528,17618299,0.00309,41850,Netherlands,NLD,NL,528,Europe,Western Europe,33670.0,523.2640,1355.2538,72,67.1,1150,303798,17134872
19,20,348,10156239,0.01896,93028,Hungary,HUN,HU,348,Europe,Eastern Europe,91260.0,111.2891,288.2386,94,68.3,660,174354,9660351
18,19,705,2119675,-0.00008,20273,Slovenia,SVN,SI,705,Europe,Southern Europe,20136.4,105.2658,272.6385,149,69.7,145,38305,2078938
17,18,36,26439111,0.01000,7692024,Australia,AUS,AU,36,Oceania,Australia and New Zealand,7692020.0,3.4372,8.9024,55,71.6,1825,482114,25499884
16,17,191,4008617,-0.00539,56594,Croatia,HRV,HR,191,Europe,Southern Europe,55960.0,71.6336,185.5311,130,72.1,296,78195,4105267
15,16,840,339996563,0.00505,9372610,United States,USA,US,840,North America,Northern America,9147420.0,37.1686,96.2666,3,72.8,24105,6367867,331002651
14,15,100,6687717,-0.01390,110879,Bulgaria,BGR,BG,100,Europe,Eastern Europe,108560.0,61.6039,159.5540,110,75.6,525,138690,6948445
13,14,246,5545475,0.00085,338424,Finland,FIN,FI,246,Europe,Northern Europe,303940.0,18.2453,47.2553,118,77.2,428,113066,5540720
12,13,178,6106869,0.02285,342000,Republic of the Congo,COG,CG,178,Africa,Sub-Saharan Africa,341500.0,17.8825,46.3156,113,78.8,435,114915,5518087
11,12,266,2436566,0.01991,267668,Gabon,GAB,GA,266,Africa,Sub-Saharan Africa,257670.0,9.4561,24.4914,146,80.0,178,47023,2225734
10,11,372,5056935,0.00673,70273,Ireland,IRL,IE,372,Europe,Northern Europe,68890.0,73.4059,190.1214,125,81.0,400,105669,4937786
9,10,724,47519628,-0.00082,505992,Spain,ESP,ES,724,Europe,Southern Europe,499556.6,95.1236,246.3702,32,81.6,3815,1007816,46754778
8,9,703,5795199,0.02689,49037,Slovakia,SVK,SK,703,Europe,Eastern Europe,49035.0,118.1849,306.0990,116,82.2,449,118613,5459642
7,8,516,2604172,0.01448,825615,Namibia,NAM,NaN,516,Africa,Sub-Saharan Africa,823290.0,3.1631,8.1925,145,83.4,212,56004,2540905
6,7,440,2718352,-0.01153,65300,Lithuania,LTU,LT,440,Europe,Northern Europe,62620.0,43.4103,112.4326,142,83.4,227,59967,2722289
5,6,233,1322765,-0.00249,45227,Estonia,EST,EE,233,Europe,Northern Europe,42750.0,30.9419,80.1394,156,84.4,112,29587,1326535
4,5,276,83294633,-0.00090,357114,Germany,DEU,DE,276,Europe,Western Europe,349390.0,238.4002,617.4564,19,92.5,7746,2046277,83783942
3,4,642,19892812,0.01188,238391,Romania,ROU,RO,642,Europe,Eastern Europe,230080.0,86.4604,223.9325,64,95.0,1828,482907,19237691
2,3,616,41026067,0.02933,312679,Poland,POL,PL,616,Europe,Eastern Europe,306130.0,134.0152,347.0993,37,96.0,3633,959737,37846611
1,2,40,8958960,0.00216,83871,Austria,AUT,AT,40,Europe,Western Europe,82520.0,108.5671,281.1889,100,96.8,872,230358,9006398
0,1,203,10495295,0.00013,78865,Czech Republic,CZE,CZ,203,Europe,Eastern Europe,77198.5,135.9521,352.1158,89,181.7,1946,514079,10708981